BEGIN;

DROP TABLE IF EXISTS player CASCADE;
DROP TABLE IF EXISTS game CASCADE;
DROP TABLE IF EXISTS game_genre CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS session_player CASCADE;
DROP TABLE IF EXISTS player_pass CASCADE;

COMMIT;
