create or replace procedure init()
as $$
begin
	DROP TABLE IF EXISTS JOGO_ESTAT;
	DROP TABLE IF EXISTS JOGADOR_ESTAT;
	DROP TABLE IF EXISTS AMIZADE;
	DROP TABLE IF EXISTS JUNTARCONVERSA;
	DROP TABLE IF EXISTS CRIARCONVERSA;
	DROP TABLE IF EXISTS ASSOCIARCRACHA;
	DROP TABLE IF EXISTS MENSAGENS;
	DROP TABLE IF EXISTS CONVERSA;
	DROP TABLE IF EXISTS CRACHA;
	DROP TABLE IF EXISTS PONTUACAOMULTIJOGADOR;
	DROP TABLE IF EXISTS PARTIDAMULTIJOGADOR;
	DROP TABLE IF EXISTS PARTIDANORMAL;
	DROP TABLE IF EXISTS JOGAR;
	DROP TABLE IF EXISTS PARTIDA;
	DROP TABLE IF EXISTS COMPRA;
	DROP TABLE IF EXISTS JOGOS;
	DROP TABLE IF EXISTS JOGADOR;
end;
$$ language plpgsql;

create or replace procedure deleteView()
as $$
begin
	drop view if exists jogadorTotalInfo;
end;
$$ language plpgsql;
begin
	call init();
	call deleteView();

COMMIT;