begin;
delete from CLIENTEVIAGEM;
delete from VIAGEM;
delete from PERIODOACTIVO;
delete from CORVEICULO;
delete from CONTACTO;
delete from CONDUTORHABILITADO;
delete from CONDUTOR;
delete from VEICULO;
delete from PROPRIETARIO;
delete from TIPOVEICULO;
delete from PESSOA;
commit;